seed: 2025
data:
  tickers: 
    - "600519.SS"
    - "600036.SS"
    - "601318.SS"
    - "300750.SZ"
    - "000858.SZ"
    - "000333.SZ"
    - "601166.SS"
    - "600309.SS"
    - "002594.SZ"
    - "601012.SS"
  index: "000001.SS"
  start: "2016-01-01"
  end: "2024-12-31"
  out_dir: "data"

features:
  window_T: 60
  horizons: [1, 3, 5]
  quantiles: [0.1, 0.5, 0.9]
  winsor_pct: 0.01
  zscore_window: 252

split:
  train_end: "2019-12-31"
  val_end: "2022-12-31"
  test_end: "2024-12-31"

