seed: 2025
data:
  tickers: 
    - "600519.SS"  # 贵州茅台
    - "600036.SS"  # 招商银行
    - "601318.SS"  # 中国平安
    - "000858.SZ"  # 五粮液
    - "000333.SZ"  # 美的集团
    - "601166.SS"  # 兴业银行
    - "600309.SS"  # 万华化学
    - "600000.SS"  # 浦发银行
    - "600028.SS"  # 中国石化
    - "600104.SS"  # 上汽集团
    - "000002.SZ"  # 万科A
    - "000001.SZ"  # 平安银行
    - "600016.SS"  # 民生银行
    - "600019.SS"  # 宝钢股份
    - "600050.SS"  # 中国联通
  index: "000001.SS"
  start: "1994-01-01"
  end: "2024-12-31"
  out_dir: "data"

features:
  window_T: 60
  horizons: [1, 7, 30]  # 日线、周线、月线
  quantiles: [0.1, 0.5, 0.9]
  winsor_pct: 0.01
  zscore_window: 252

split:
  train_end: "2019-12-31"
  val_end: "2022-12-31"
  test_end: "2024-12-31"

